<?php

namespace Container5F7nQKS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TDR8AXLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tDR8AXL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tDR8AXL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProgramController::autocomplete' => ['privates', '.service_locator.FaUv1vw', 'get_ServiceLocator_FaUv1vwService', true],
            'App\\Controller\\ProgramController::search' => ['privates', '.service_locator.FaUv1vw', 'get_ServiceLocator_FaUv1vwService', true],
            'App\\Controller\\ProgramController::show' => ['privates', '.service_locator.6Q3SUSI', 'get_ServiceLocator_6Q3SUSIService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\ProgramController:autocomplete' => ['privates', '.service_locator.FaUv1vw', 'get_ServiceLocator_FaUv1vwService', true],
            'App\\Controller\\ProgramController:search' => ['privates', '.service_locator.FaUv1vw', 'get_ServiceLocator_FaUv1vwService', true],
            'App\\Controller\\ProgramController:show' => ['privates', '.service_locator.6Q3SUSI', 'get_ServiceLocator_6Q3SUSIService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\ProgramController::autocomplete' => '?',
            'App\\Controller\\ProgramController::search' => '?',
            'App\\Controller\\ProgramController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ProgramController:autocomplete' => '?',
            'App\\Controller\\ProgramController:search' => '?',
            'App\\Controller\\ProgramController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
