<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5F7nQKS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5F7nQKS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5F7nQKS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5F7nQKS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5F7nQKS\App_KernelDevDebugContainer([
    'container.build_hash' => '5F7nQKS',
    'container.build_id' => 'dae60025',
    'container.build_time' => 1610712689,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5F7nQKS');
